# Generated by Django 4.2.1 on 2023-06-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, verbose_name='Company')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('raw_material', models.CharField(max_length=20, verbose_name='Raw Material')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'db_table': 'supervisor',
                'ordering': ['name', '-last_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.client'),
        ),
    ]
